name: Run Playwright Script

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      # Install Playwright browsers
      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Create videos directory
        run: mkdir videos

      - name: Run Playwright script
        run: npm test

      # Upload the recorded video as an artifact
      - name: Upload videos
        uses: actions/upload-artifact@v2
        with:
          name: recorded-videos
          path: videos/
